### ISSUE TITLE
Button name is 'suchen' in any language.

### ISSUE THREAD

**Issue by rfj74** [nanoflow/search_member#1]
The name remains the same in any language. In the search-member.php the code on line 64 uses a hard coded button name.

`    $form->addSubmitButton('btn_search', 'suchen', array('icon' => 'fa-search'));`

This should be (imo),

`    $form->addSubmitButton('btn_search', $gL10n->get('SYS_SEARCH'), array('icon' => 'fa-search'));`

On my installation it is working. Further more I translated the plugin into Dutch, [nl.xml.zip](https://github.com/nanoflow/search_member/files/15339831/nl.xml.zip), so maybe you like to add this to the languages.

I used the latest version from the Admidio website, version 1.0.2.

Kind regards,
Richard.

**Comment by nanoflow** [comment]
Hi Richard, thanks for reporting, I released a new version (1.0.3) fixing this bug. Thank you for the translation.

**Comment by rfj74** [comment]
Hi Nanoflow, thank you for the update.
